### ISSUE TITLE
This Repository is not licensed

### ISSUE THREAD

**Issue by Drakulix** [webgravel/common-ssl#1]
Hey there,
this project is one of the only and working ssl-psk extensions for python.
I have created (an currently unreleased) kodi (xbmc) addon using this library and I would love to distribute a standalone working version of it including pre-compiled binaries of this library, instead of leaving out this library completely, which is what I need to do in its current state: http://choosealicense.com/no-license/

I would be absolutely lovely if you could add any license, that would allow distributing an unmodified (pre-compiled) version or at least any license, that clarifies this situation for any possible users.

Thanks for your time.
Greetings,
Drakulix

**Comment by zielmicha** [comment]
Fixed in 128a5979c7ce17da82373a161d657ba038e60cd7

**Comment by Drakulix** [comment]
big thanks.
